services:
#  jaeger:
#    image: jaegertracing/all-in-one:latest
#    ports:
#      - 6831:6831/udp
#      - 6832:6832/udp # jaeger-collector HTTP server (tracer provider)
#      - 16686:16686   # HTTP server (browser UI)

  postgres:
    image: postgres:14.4
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: order
    container_name: 'postgresql-container-order'
    #volumes:
    #  - ./postgresql/data:/var/lib/postgresql/data # том для того, чтобы при перезапуске контейнера все данные сохранялись
    # - ./postgres.conf:/etc/postgresql/postgresql.conf # конфиг БД
    #command: postgres -c config_file=/etc/postgresql/postgresql.conf
    ports:
      - 5432:5432
    restart: always

  pgbouncer:
    image: bitnami/pgbouncer
    environment:
      POSTGRESQL_USERNAME: user
      POSTGRESQL_PASSWORD: password
      POSTGRESQL_DATABASE: order
      POSTGRESQL_HOST: localhost
      POSTGRESQL_PORT: 5432
      PGBOUNCER_POOL_MODE: transaction
      PGBOUNCER_PORT: 6432
      PGBOUNCER_BIND_ADDRESS: localhost
      PGBOUNCER_MAX_CLIENT_CONN: 1000
volumes:
  data-volume: